### ISSUE TITLE
Ability to enable "First Name" and "Last Name" fields in the Additional Participant Profile 

### ISSUE THREAD

**Issue by cristina-p** [twomice/com.joineryhq.groupreg#19]
Is there any way to **enable** the fields "**_First Name_**" and "**_Last Name_**" in the **Additional Participant Profile** of the Event configuration, so that they can **be updated** by the Primary Participant during the event registration, as it can be done for the "_Email_" field?

**Comment by twomice** [comment]
This extension actually makes a point of disabling those fields, with this rationale:

- Changing the name of a contact from, say, "Bill Brown" to "Mary Smith" is usually a bad idea:
  - Bill Brown and Mary Smith are almost certainly two different real-world human beings.
  - If Bill Brown is an existing contact, he has a whole history of participation in your organization; this history is not true for Mary Smith.
- Name changes such as this _are_ possible through the civicrm back-office area, but that area is usually reserved for trained organization staff, who should be aware of the potential problem of name changes, and are expected to make only the changes that are actually true for the real human being named Bill Brown (e.g. he now goes by "William")
- On the other hand, public users who are registering for an event are far less likely to understand these issues, and far more likely to simply change a contact name for the "wrong reason" -- i.e. because today they want to register their daughter Mary instead of their son Bill.

For these reasons, I'm quite hesitant to support this feature request. @cristina-p , considering the above concerns, what are your thoughts on the matter?

**Comment by cristina-p** [comment]
Yes, I agree on that. But I was wondering what are the fields to identify a unique Contact, because I've seen that when a contact is selected, if the email address changes, the extension creates a new contact, instead of updating the email address of the contact selected. Is that the right behaviour?
If that were the right behaviour, if the user was to change the First Name and Last Name, these fields will be updated for the contact with that email address specified, and the user won't be replacing one contact with all his history for another, as a new contact will be created. Is that right?

In our specific case, we have registered children, whose Email address needs to be updated, and we want the user to update it during an Event registration. So we would need the ability to update this field for the Contact selected, but not to create a new contact.

**Comment by twomice** [comment]
> ... because I've seen that when a contact is selected, if the email address changes, the extension creates a new contact, instead of updating the email address of the contact selected. Is that the right behaviour?

By design, the extension _should not_ be creating a new contact in this situation (i.e., when you have selected an existing contact from the list of related contacts).

Can you confirm that this is really happening that way? If so, I'll treat that as a bug and work on a fix.

Thanks!

**Comment by cristina-p** [comment]
Sorry for the late reply.
Yes, I confirm that this is happening: the extension creates a new contact when updating the email address of an existing contact selected from the list of related contacts.

**Comment by twomice** [comment]
> I confirm that this is happening: the extension creates a new contact when updating the email address of an existing contact selected from the list of related contacts.

@cristina-p Thanks for reporting this. To help me keep everything organized (for my own workflow and for others who may come to this issue queue later), would you please create a new ticket for that specific issue. (The current ticket, per the title, relates to editing/locking the First and Last Name fields.)
