### ISSUE TITLE
 Related Contact list is hidden for non-Administrator users

### ISSUE THREAD

**Issue by cristina-p** [twomice/com.joineryhq.groupreg#21]
It seems that the **Related Contact list** for the Additional Participants only appears for **an Administrator user**:

![image](https://github.com/twomice/com.joineryhq.groupreg/assets/36039284/582ffec6-da76-4cf7-9326-c7ad78026a39)

As for an **non-Administrator** user the **Related Contact** list is **hidden**, as you can see in the following screen for the Additional Participant:

![image](https://github.com/twomice/com.joineryhq.groupreg/assets/36039284/986bca04-8ccb-41e8-8838-1fa219dc76e2)

Is this the expected behaviour?
Thank you!

**Comment by twomice** [comment]
Yes, this is expected, in certain situations (which is probably your situation).

The "Select a person" field will only contain individuals for whom the current user has edit permissions (see CiviCRM Docs [Relationships: Relationship permissions](https://docs.civicrm.org/user/en/latest/organising-your-data/relationships/#relationship-permissions)).

For example imagine the current user has this under their Relationships tab (red arrows indicate the "edit" permission):

![relationships](https://github.com/twomice/com.joineryhq.groupreg/assets/759449/db984211-43b4-44db-9dde-963b1e7953ba)

For this user, the contact "Cooper, Alexa" will appear in the "Select a person" list, but the contact "Adams, Maxwell" will not.

Furthermore (and I expect this is your situation), if the current user has no such related contacts at all (i.e., the "Select a person" list would be empty), then the "Select a person" field is not displayed at all, since it would serve no purpose.

In case it's not obvious, the rationale here is that the user will, in the process of registration, be able to edit the contact information for the selected contact. As such, we aim to honor civicrm's configured permissions, in order to prevent unauthorized modification of contact data.
